version: "3.9"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Открываем порт 3000
    volumes:
      - .:/app # Для локальной разработки (если требуется)
      - /app/node_modules
    environment:
      NODE_ENV: production